In [2]:
import numpy as np

In [3]:
a = np.array([8,4,5])
b = np.array([1,2,3])
print('두 벡터의 합 :', a+b)
print('두 벡터의 차 :', a-b)

두 벡터의 합 : [9 6 8]
두 벡터의 차 : [7 2 2]


In [4]:
a = np.array([[10,20,30,40],[50,60,70,80]])
b = np.array([[5,6,7,8],[1,2,3,4]])
print('두 행렬의 합 :')
print(a + b)
print('두 행렬의 차 :')
print(a - b)

두 행렬의 합 :
[[15 26 37 48]
 [51 62 73 84]]
두 행렬의 차 :
[[ 5 14 23 32]
 [49 58 67 76]]


In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print('두 벡터의 내적 :', np.dot(a,b))

두 벡터의 내적 : 32


In [7]:
a = np.array([[1,3],[2,4]])
b = np.array([[5,7],[6,8]])
print('두 행렬의 행렬곱 :')
print(np.matmul(a,b))

두 행렬의 행렬곱 :
[[23 31]
 [34 46]]
