In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [17]:
x,y = zip(['a', 1], ['b', 2], ['c', 3])
print('x 데이터 :', x)
print('y 데이터 :', y)

# 각 데이터에서 첫번째로 등장한 원소들끼리 묶고, 두번째로 등장한 원소들끼리 묶는다

x 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [18]:
sequences = [['a', 1], ['b', 2], ['c', 3]]
x,y = zip(*sequences)
print('x 데이터 :', x)
print('y 데이터 :', y)

x 데이터 : ('a', 'b', 'c')
y 데이터 : (1, 2, 3)


In [19]:
# 데이터프레임을 이용하여 분리하기

In [20]:
values = [['당신에게 드리는 마지막 혜택!', 1],
['내일 뵐 수 있을지 확인 부탁드...', 0],
['도연씨. 잘 지내시죠? 오랜만입...', 0],
['(광고) AI로 주가를 예측할 수 있다!', 1]]
columns = ['메일 본문', '스팸 메일 유무']

In [21]:
df = pd.DataFrame(values, columns=columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [22]:
x = df['메일 본문']
y = df['스팸 메일 유무']

In [23]:
print('x 데이터 :', x.to_list())
print('y 데이터 :', y.to_list())

x 데이터 : ['당신에게 드리는 마지막 혜택!', '내일 뵐 수 있을지 확인 부탁드...', '도연씨. 잘 지내시죠? 오랜만입...', '(광고) AI로 주가를 예측할 수 있다!']
y 데이터 : [1, 0, 0, 1]


In [24]:
# Numpy를 이용하여 분리하기

In [25]:
np_array = np.arange(0,16).reshape((4,4))
print('전체 데이터 :')
print(np_array)

전체 데이터 :
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [26]:
x = np_array[:, :3]
y = np_array[:,3]

print('x 데이터 :')
print(x)
print('y 데이터 :', y)

x 데이터 :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y 데이터 : [ 3  7 11 15]


In [27]:
# 사이킷 런을 이용하여 분리하기

In [28]:
# 임의로 x와 y 데이터를 생성
x, y = np.arange(10).reshape((5, 2)), range(5)

print('x 전체 데이터 :')
print(x)
print('y 전체 데이터 :')
print(list(y))

x 전체 데이터 :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y 전체 데이터 :
[0, 1, 2, 3, 4]


In [29]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=1234) # random_state 값에 따라 다른 결과 출력

In [30]:
print('X 훈련 데이터 :')
print(X_train)
print('X 테스트 데이터 :')
print(X_test)

X 훈련 데이터 :
[[2 3]
 [4 5]
 [6 7]]
X 테스트 데이터 :
[[8 9]
 [0 1]]


In [31]:
print('y 훈련 데이터 :')
print(y_train)
print('y 테스트 데이터 :')
print(y_test)

y 훈련 데이터 :
[1, 2, 3]
y 테스트 데이터 :
[4, 0]
